### ISSUE TITLE
Using only wildcard does not match anything

### ISSUE THREAD

**Issue by mtreuberg** [wickedOne/phrase-tag-bundle#57]
Hello,

it seems that tagging all keys at once is not possible with the wilcard `*`.

I tried to tag all keys by using this command:
```
$ bin/console phrase:keys:tag --query-key="*" --tag my-nice-tag --dry-run
09:39:30 INFO      [http_client] Request: "GET https://api.phrase.com/v2/projects/.../keys?page=1&per_page=100&q=*"
09:39:30 INFO      [http_client] Response: "200 https://api.phrase.com/v2/projects/.../keys?page=1&per_page=100&q=*"
your query does not match any keys
```

Without the `--dry-run` the result is: `successfully tagged 0 keys with "my-nice-key"`

I also tried without the query key, but that also doesn't work:
```
bin/console phrase:keys:tag --tag my-nice-tag --dry-run
no query parameters provided
```

Am I using it wrong or is this indeed a bug?

Best regards,
Matthias

**Comment by wickedOne** [comment]
hi @mtreuberg 

to be honest i've never tried just using a wildcard in order to match all keys, but the phrase api documentation does not mention it's not possible

please do keep in mind that, even when it works, `Search is limited to 10000 results` so i don't know about the size of your project...

so you're not using it wrong, but it might be either a phrase limitation or an implementation defect on my side: i'll have to do a little investigation so give me a bit of time to get back to you

**Comment by mtreuberg** [comment]
Hi @wickedOne,

thanks for the quick reply. After all I found out how to assign the same tag to all keys via the Phrase Web UI (just couldn't find it before). So no rush here.

Still I think it would be useful if it worked, so it would be interesting to hear if it's a Phrase limitation or not.

Thank you for creating this project in the first place!

**Comment by wickedOne** [comment]
> Thank you for creating this project!

you're very welcome :-)

alright, did a bit of digging and phrase indeed doesn't allow you to match all keys by just using a wildcard `*`, *however* it does allow you to match all keys by simply omitting the query.

the linked pull request allows you to do just that, so after it's merged & tagged you can use:

```bash
composer update wickedone/phrase-tag-bundle
```

and you should be good to go. given your example it would be (and keep in mind it only displays the first 100 matches):

```bash
bin/console phrase:keys:tag --tag my-nice-tag --dry-run
```

**Comment by mtreuberg** [comment]
@wickedOne Thank you very much!
